### ISSUE TITLE
\tikzstyle is obsolete

### ISSUE THREAD

**Issue by samcarter** [cpierquet/tkz-bernoulli#1]
`\tikzstyle` is obsolete, have a look at `\tikzset` instead.

So instead of 

```
\tikzstyle{foo}=[<tikz options>]
```

it should be 

```
\tikzset{foo/.style={<tikz options>},...}
```

**Comment by cpierquet** [comment]
Hi- Dad habit to continue using `\tikzstyle` :-)
I'm going to migrate my packages to `\tikzset` !!

**Comment by cpierquet** [comment]
Done :-)
